version: '3.1'
services:
  sonarqube:
    container_name: sonarqube
    image: "sonarqube:8.9.7-community"
    ports:
      - "9000:9000"
    volumes:
     - sonarqube_data:/opt/sonarqube/data
     - sonarqube_extensions:/opt/sonarqube/extensions
     - sonarqube_logs:/opt/sonarqube/logs
  
volumes:
  sonarqube_logs:
  sonarqube_extensions:
  sonarqube_data:
 
