version: '3.1'
services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8081:8081"
      
volumes:
  nexus-data:


   
